# Generated by Django 5.1 on 2024-08-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="slug",
            field=models.CharField(default="18fie250", max_length=8, unique=True),
        ),
    ]
