# Generated by Django 5.1 on 2024-08-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0002_alter_url_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="slug",
            field=models.CharField(default="ne0imu7k", max_length=8, unique=True),
        ),
    ]
